folio-org/ui-vendors

src/Accounts/AccountsForm.js
src/Main/Main.js
src/VendorViews/FormVendor.js
src/VendorViews/ViewVendor.js

- fixed lint errors in AccountsForm, FormVendor and ViewVendor
- updated perms.vendor.item.post to vendor.item.post

updated button permission and fixed some lint errors

---

.stripesclirc
src/ContactInformation/ContactInfoFormGroup/Urls.js
src/ContactInformation/ContactInfoViewGroup/AddressInfoView.js
src/ContactInformation/ContactInfoViewGroup/UrlsView.js
src/ContactPeople/ContactPeopleView.js
src/EdiInformation/EdiInformationForm.js
src/EdiInformation/EdiInformationView.js
src/Interface/InterfaceForm.js
src/Interface/InterfaceView.js
src/Main/Main.js
src/Summary/SummaryForm.js
src/Summary/SummaryView.js
src/Utils/BoolToCheckbox.js
src/Utils/FilterConfig.js
src/VendorInformation/VendorInformationForm.js
src/VendorInformation/VendorInformationView.js
src/VendorViews/FormVendor.js
src/VendorViews/ViewVendor.js

- added dropdown filter
- moved fields
- changed bool to checkbox
- show password in IDE section

merge dev to master

---

src/EdiInformation/EdiInformationForm.js
src/Interface/InterfaceForm.js
src/Utils/FilterConfig.js
stripes.config.js.local

- import back toggle password component
- temporary removed language and country

Fixed for vendor slow down

---

src/Main/Main.css
src/Main/Main.js

removed SearchAndSort div wrapper

updated SearchAndSort properties and declared props

---

CHANGELOG.md

updated stripes form version to 0.9.0

 Release v1.0.1

---

CHANGELOG.md
src/Agreements/AgreementsView.js
src/ContactInformation/ContactInfoFormGroup/AddressInfo.js
src/ContactInformation/ContactInfoFormGroup/EmailAddresses.js
src/ContactInformation/ContactInfoFormGroup/PhoneNumbers.js
src/ContactInformation/ContactInfoFormGroup/Urls.js
src/ContactInformation/ContactInfoViewGroup/AddressInfoView.js
src/ContactPeople/ContactPeopleForm.js
src/EdiInformation/EdiInformationForm.js
src/Summary/SummaryForm.js
src/Summary/SummaryView.js
src/Utils/HandleErrors.js
src/VendorViews/FormVendor.js
src/VendorViews/ViewVendor.js

* Converted category dropdown to multi select. Ref: UIV-4.
* Fixed vendor status error highlight. Ref: UIV-12.
* Fixed Agreements discount display. Ref: UIV-3.
* Changed field name ERP code to Accounting Code. UIV-2
* Updated Vendor EDI Code and Library EDI Code component type to TextField. Ref: UIV-5.
* Update component UIV-5
* Added tags, ref: UIV-27.

dev to master

---

src/Main/Main.js
src/VendorInformation/VendorInformationForm.js
src/VendorViews/ViewVendor.js

changed vendor currencies drop down to multi select.

UIV-33 dev to master

---

src/Summary/SummaryForm.js
src/VendorViews/ViewVendor.js

- removed categories data inside address
- disabled sans code until mod-vendor schema is updated

UIV-52 Fixed Vendor Form submit error

---

src/ContactInformation/ContactInfoFormGroup.css
src/ContactInformation/ContactInfoFormGroup/AddressInfo.js
src/ContactInformation/ContactInfoFormGroup/EmailAddresses.js
src/ContactInformation/ContactInfoFormGroup/PhoneNumbers.js
src/ContactInformation/ContactInfoFormGroup/Urls.js
src/ContactInformation/ContactInfoViewGroup/AddressInfoView.js
src/ContactPeople/ContactPeopleForm.css
src/ContactPeople/ContactPeopleForm.js
src/ContactPeople/ContactPeopleForm/PhoneNumbersCP.js
src/ContactPeople/ContactPeopleForm/index.js
src/ContactPeople/ContactPeopleView.css
src/ContactPeople/ContactPeopleView.js
src/Main/Main.css
src/VendorViews/FormVendor.js
src/VendorViews/ViewVendor.js

Updated view and styling for contact people

UIV-30 contact people multi options

---

src/ContactInformation/ContactInfoViewGroup/AddressInfoView.js
src/VendorViews/ViewVendor.js

clean up row padding, changed open accordion back to summary section.

UIV-21 Primary address

---

package.json

UIV-66 permission update

---

translations/ui-vendors/en_US.json

Please do not manually merge this pull request.  It will either be automatically merged or withdrawn.

Update translation strings as of 20190130T201814

---

src/ContactInformation/ContactInfoFormGroup/AddressInfo-backup.js
src/ContactInformation/ContactInfoFormGroup/AddressInfo.js
src/ContactInformation/ContactInfoViewGroup/EmailView.js
src/ContactInformation/ContactInfoViewGroup/PhoneNumbersView.js
src/ContactInformation/ContactInfoViewGroup/UrlsView.js
src/ContactInformation/ContactInformationForm.js
src/ContactPeople/ContactPeopleForm.css
src/ContactPeople/ContactPeopleForm.js
src/ContactPeople/ContactPeopleFormGroup/AdditionalAddress.js
src/ContactPeople/ContactPeopleFormGroup/index.js
src/ContactPeople/ContactPeopleView.css
src/ContactPeople/ContactPeopleView.js
src/Main/Main.css
src/MultiForms/AddressesMF.js
src/MultiForms/EmailsMF.js
src/MultiForms/PhoneNumbersMF.js
src/MultiForms/UrlsMF.js
src/MultiForms/index.js
src/VendorViews/ViewVendor.js

Schema was updated based on (MODVEND-72)[https://issues.folio.org/browse/MODVEND-72]. flatten address, email, phone_number, url models.
- Updated Contact Information Section and Contact People section
- Updated property NAME that maps to the database schema.
- Updated reconstruct component for address, urls, phone and email to be reuse in contact information and contact people making it easy to maintain.
- Are the JIRAs under …

UIV-21 update schema address phone url email

---

src/ContactPeople/ContactPeopleView.js
src/MultiForms/AddressesMF.js
src/MultiForms/EmailsMF.js
src/MultiForms/PhoneNumbersMF.js
src/MultiForms/UrlsMF.js

- Prevent duplication of address, email, phone numbers, and URLs.
- This is also related to schema update in (MODVEND-72)[https://issues.folio.org/browse/MODVEND-72]
- Updated query path for address, email, phone numbers, and URLs.
- Remove duplicate fo address, email, phone numbers, and URLs by using lodash _.uniqBy.
Ideally all of the PRs involved in …

UIV-64 auto suggest remove duplicates

---

package.json
src/ContactPeople/ContactPeopleForm.js
src/ContactPeople/ContactPeopleView.js
src/EdiInformation/EdiInformationForm.js
src/EdiInformation/EdiInformationView.js
src/Main/Main.js
src/MultiForms/AddressesMF.js
src/MultiForms/EmailsMF.js
src/MultiForms/UrlsMF.js
src/VendorViews/ViewVendor.js

https://issues.folio.org/browse/MODVEND-85
https://issues.folio.org/browse/MODVEND-86
* Updated NAME property to match the updated schema for contacts, contact information and edi.
* Updated query for views in contacts, contact information and edi.
* Remove primary fields in contact person.
Learned how to add sample data in my local using load-data.pl script
- https://github.com/folio-org/folio-install/blob/master/load-data.pl
and removing data by adding purge=true
[/_/proxy/tenants/diku/install?purge=true](/_/proxy/tenants/diku/install?purge=true)
`[
{
"id": "mod-vendors-1.1.0-SNAPSHOT",
"action": "disable"
}
]`
- Does this introduce …

UIV-76 contact person schema to contacts

---

package.json
src/ContactPeople/ContactPeopleForm.js
src/ContactPeople/ContactPeopleView.js
src/EdiInformation/EdiInformationForm.js
src/EdiInformation/EdiInformationView.js
src/Main/Main.js
src/MultiForms/AddressesMF.js
src/MultiForms/EmailsMF.js
src/MultiForms/UrlsMF.js
src/VendorViews/ViewVendor.js

Reverts folio-org/ui-vendors#137

Revert "UIV-76 contact person schema to contacts"

---

package.json
src/ContactPeople/ContactPeopleForm.js
src/ContactPeople/ContactPeopleView.js
src/EdiInformation/EdiInformationForm.js
src/EdiInformation/EdiInformationView.js
src/Main/Main.js
src/MultiForms/AddressesMF.js
src/MultiForms/EmailsMF.js
src/MultiForms/UrlsMF.js
src/VendorViews/ViewVendor.js

https://issues.folio.org/browse/MODVEND-85
https://issues.folio.org/browse/MODVEND-86
* Updated NAME property to match the updated schema for contacts, contact information and edi.
* Updated query for views in contacts, contact information and edi.
* Remove primary fields in contact person.
Learned how to add sample data in my local using load-data.pl script
- https://github.com/folio-org/folio-install/blob/master/load-data.pl
and removing data by adding purge=true
[/_/proxy/tenants/diku/install?purge=true](/_/proxy/tenants/diku/install?purge=true)
`[
{
"id": "mod-vendors-1.1.0-SNAPSHOT",
"action": "disable"
}
]`
- Does this introduce …

Uiv 76 contact person schema to contacts

---

package.json

https://issues.folio.org/browse/UIV-75
Updated permission labels
All = "Vendor: Can create, view, update and delete"
get = "Vendor: Can view item"
put = "Vendor: Can update item"
delete = "Vendor: Can delete item"
create = "Vendor: Can create item"
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

UIV-75 updated labels for vendor permission

---

src/Agreements/AgreementsForm.js
src/ContactPeople/ContactPeopleForm.js
src/EdiInformation/EdiInformationForm.js
src/Interface/InterfaceForm.js
src/MultiForms/AddressesMF.js
src/MultiForms/UrlsMF.js
src/Utils/Validate.js
translations/ui-vendors/en.json

https://issues.folio.org/browse/UIV-78
Set validation to the following
**Rules:**
* http(s)://
* HTTP(S)://
* ftp(s)://
* FTP(S)://
**Forms to check:**
* Contact People URL
* EDI Information > FTP Details > Server Address
* Interface > URL
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

UIV-78 Added URL validation for fields

---

src/Agreements/AgreementsForm.js

- Agreements name field should only validate  as "required field" condition, right now its checking/validating URL.
- Missing url validation to agreements URL|reference_url field
- Agreements name field: replace validation from "isValidURL" to "Required"
- Agreements  URL|reference_url field: added "isValidURL" validation
Ideally all of the PRs involved …

UIV-78 URL validation

---

src/Main/Main.js

Vendor form throwing error on submit if you select value in FTP format.
Change all values to all caps
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

UIV-76 bug fix: updated FTP value

---

index.js
src/Settings/index.js

https://issues.folio.org/browse/FOLIO-1824
https://issues.folio.org/browse/UIOR-126
Updated settings path
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

UIV-75 UIOR-126 FOLIO-1824 Updated settings path

---

src/VendorInformation/VendorInformationForm.js

https://issues.folio.org/browse/UIV-61
Added Expected Receipt Interval in View and Form
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …

Uiv 61 add field expected receipt interval

---

package.json

https://issues.folio.org/browse/UIV-75
replace "item" with "record"
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  
While it's helpful …

UIV-75 replace "item" with "record"

---

src/ContactPeople/ContactPeopleForm.js
src/ContactPeople/ContactPeopleView.js
src/MultiForms/EmailsMF.js
src/VendorViews/ViewVendor.js

https://issues.folio.org/browse/UIV-83
- Show categories in on contact people in form and view
- Fix multi-select categories for contact people form
- Fix categories in contact people view
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …

UIV-83 contact people category

---

src/Main/Main.js

https://issues.folio.org/browse/UIV-69
- updated SearchAndSort packageInfo property, to detect if its plugin or not.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

UIV-69 updated SearchAndSort packageInfo property

---

package.json

https://issues.folio.org/browse/UIV-90
- updated permission name for settings page
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  
While …

Uiv 90 missing settings page

---

translations/ui-vendors/it_IT.json

Please do not manually merge this pull request.  It will either be automatically merged or withdrawn.

Update translation strings as of 20190313T213403

---

src/Main/Main.js

https://issues.folio.org/browse/UIV-49
- updated duplicate option
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  
While it's helpful for …

UIV-49 removed duplicated library edi code type option

---

src/ContactPeople/ContactPeopleForm.js
src/ContactPeople/ContactPeopleView.js

https://issues.folio.org/browse/UIV-102
updated condition for contact, if state.contactArrState is empty return empty array.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

UIV-102 contact people
